# Generated by Django 4.1.6 on 2023-03-29 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0002_commentaire_reponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='lesson',
            new_name='nom_lesson',
        ),
    ]
